### ISSUE TITLE
ie6下选择完图片后会提示下载文件

### ISSUE THREAD

**Issue by superfighter** [kissygalleryteam/uploader#112]
下载的目标文件是请求的后端地址。
推断原因是Header中的content-type导致，其中content-type: application/text;charset=UTF-8或者content-type: application/json;charset=UTF-8都无法正常上传；后端改为content-type: text/html;charset=UTF-8，ie6能正常上传了。

**Comment by minghe** [comment]
是的，服务器需要根据上传类型更改头
