### ISSUE TITLE
IE在文件过大的413错误处理

### ISSUE THREAD

**Issue by songsiqi** [kissygalleryteam/uploader#150]
IE8-一直显示“等待上传，请稍后”，没有触发error事件
IE9则直接显示错误，没有文案：
![4718b93b-55f6-4fc7-a066-d9a92daa4150](https://cloud.githubusercontent.com/assets/3634329/3609436/d1eee8ac-0d7a-11e4-8f10-2b2fa458374d.png)

**Comment by minghe** [comment]
使用3.0.3
