### ISSUE TITLE
2.0.2 在ie下面添加任何事件侦听没反应的

### ISSUE THREAD

**Issue by nickli** [kissygalleryteam/uploader#155]
kg/uploader/2.0.2/type/iframe 模块下的 _createIframe方法里的一段判断代码
if(!self.get('domain')){
       //监听iframe的load事件
       $iframe.on('load', self._iframeLoadHandler, self);
}
把!self的！去掉就可以了。

**Comment by minghe** [comment]
已经修正 3.0.3
