### ISSUE TITLE
IE9不支持多文件上传

### ISSUE THREAD

**Issue by luodingding** [kissygalleryteam/uploader#156]
多个方式都配置了multiple:true，可IE就是不支持。
 S.use('kg/uploader/2.0.1/index,kg/uploader/2.0.1/themes/imageUploader/index,kg/uploader/2.0.1/themes/imageUploader/style.css', function (S, Uploader,ImageUploader) {
        //上传组件插件
        var plugins = 'kg/uploader/2.0.1/plugins/auth/auth,' +
                'kg/uploader/2.0.1/plugins/urlsInput/urlsInput,' +
                'kg/uploader/2.0.1/plugins/proBars/proBars,' +
                'kg/uploader/2.0.1/plugins/filedrop/filedrop,' +
                'kg/uploader/2.0.1/plugins/preview/preview,' +
                'kg/uploader/2.0.1/plugins/tagConfig/tagConfig';

        S.use(plugins,function(S,Auth,UrlsInput,ProBars,Filedrop,Preview,TagConfig){
            var uploader = new Uploader('#J_UploaderBtn',{
                //处理上传的服务器端脚本路径
                action:"upload.php",
                multiple:true
            });
            //使用主题
            uploader.theme(new ImageUploader({
                queueTarget:'#J_UploaderQueue'
            }))
            //验证插件
            uploader.plug(new Auth({
                        //最多上传个数
                        max:3,
                        //图片最大允许大小
                        maxSize:100
                    }))
                //url保存插件
                    .plug(new UrlsInput({target:'#J_Urls'}))
                //进度条集合
                    .plug(new ProBars())
                //拖拽上传
                    .plug(new Filedrop())
                //图片预览
                    .plug(new Preview())
                    .plug(new TagConfig())
            ;

            S.log('action:'+uploader.get('action'));
            S.log(uploader.get('data'));
            var auth = uploader.getPlugin('auth');
            S.log(auth.get('max'));
            S.log(auth.get('maxSize'));
        });

**Comment by minghe** [comment]
是不支持的，浏览器限制
