### ISSUE TITLE
如果想制作成淘宝后成发布商品时，不是

### ISSUE THREAD

**Issue by kingkongtown** [kissygalleryteam/uploader#158]
如下图：
http://static.open-open.com/lib/uploadImg/20120605/20120605121527_443.jpg
想做成，淘宝后台发布商品时，选择不同选择后，会分别创建一个颜色选项，上传不同颜色下的商品图片，请问要怎么创建UPLOADER对象才能有这种效果？有没有类似的DEMO可以参考呢？

**Comment by minghe** [comment]
创建多个uploader实例
