### ISSUE TITLE
NET上传成功后，删除某一图片，如何删除呢？

### ISSUE THREAD

**Issue by lilo202** [kissygalleryteam/uploader#162]
NET上传成功后，删除某一图片，如何删除呢？
看了官网的帮助文档还是有点不清楚

remove	删除队列中的图片后触发

当组件向队列添加文件时，会自动生成一个唯一id，比如'file-10'，'file-'前缀是一样的，可以通过id来获取指定的文件。

remove():删除队列中的文件

var removeFile = queue.remove(0);
S.log('删除的文件数据为：'+removeFile);

![qq 20141124155127](https://cloud.githubusercontent.com/assets/8001786/5161954/d62ab15c-73f1-11e4-8ed3-1edcf6b3ebf6.jpg)

**Comment by minghe** [comment]
监听remove事件，发个删除的ajax请求
